version: '3.7'

services:
    ma-nginx:
        container_name: ma-nginx
        image: nginx
        build:
          context: .
          dockerfile: ./nginx/Dockerfile
        restart: always
        volumes:
          # - /etc/letsencrypt:/etc/letsencrypt
          - ./etc/nginx/conf.d:/etc/nginx/conf.d
          - ./certbot/conf:/var/lib/letsencrypt
          # - ./certbot/data:/usr/share/nginx/html/letsencrypt
          # - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
          - masocket:/tmp
        networks:
          - manet
        depends_on:
          - manual-app
        ports:
          - 80:80
          - 9015:9015
          - 443:443
        # command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    manual-app:
        container_name: manual-app
        image: manual-app
        build:
          context: .
          dockerfile: ./manual_app/Dockerfile
        networks:
          - manet
        # ports:
        #   - 9015:9015
        volumes:
          - ./:/var/www/manual-app
          # - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          # - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
          - masocket:/tmp
        restart: always
        environment:
          - FLASK_APP=manual_app
          - FLASK_DEBUG=False:-True
        command: ['sh', './etc/docker-entrypoint.sh']


networks:
    manet:

volumes:
  masocket: