version: '3.7'

services:
    ma-nginx:
        container_name: ma-nginx
        image: nginx
        build:
          context: .
          dockerfile: ./nginx/Dockerfile
        restart: always
        volumes:
          - ./etc/letsencrypt:/etc/letsencrypt
          - ./etc/nginx/conf.d:/etc/nginx/conf.d
          - ./certbot/conf:/usr/local/bin
          - masocket:/tmp
        networks:
          - manet
        depends_on:
          - manual-app
        ports:
          - 80:9015
          - 443:443

    manual-app:
        container_name: manual-app
        image: manual-app
        build:
          context: .
          dockerfile: ./manual_app/Dockerfile
        networks:
          - manet
        # ports:
        #   - 9015:9015
        volumes:
          - ./:/var/www/manual-app
          - masocket:/tmp
        restart: always
        environment:
          - FLASK_APP=manual_app
          - FLASK_DEBUG=False:-True
        command: ['sh', './etc/docker-entrypoint.sh']


networks:
    manet:

volumes:
  masocket: